export const MOVIE_GENRES_GET_REQUEST = 'MOVIE_GENRES_GET_REQUEST';
export const MOVIE_GENRES_GET_SUCCESS = 'MOVIE_GENRES_GET_SUCCESS';
export const MOVIE_GENRES_GET_FAILURE = 'MOVIE_GENRES_GET_FAILURE';

export const MOVIES_BY_GENRES_GET_REQUEST = 'MOVIES_BY_GENRES_GET_REQUEST';
export const MOVIES_BY_GENRES_GET_SUCCESS = 'MOVIES_BY_GENRES_GET_SUCCESS';
export const MOVIES_BY_GENRES_GET_FAILURE = 'MOVIES_BY_GENRES_GET_FAILURE';

export const MOVIES_FEATURED_GET_REQUEST = 'MOVIES_FEATURED_GET_REQUEST';
export const MOVIES_FEATURED_GET_SUCCESS = 'MOVIES_FEATURED_GET_SUCCESS';
export const MOVIES_FEATURED_GET_FAILURE = 'MOVIES_FEATURED_GET_FAILURE';

export const MOVIE_DETAIL_CLEAR = 'MOVIE_DETAIL_CLEAR';
export const MOVIE_DETAIL_GET_REQUEST = 'MOVIE_DETAIL_GET_REQUEST';
export const MOVIE_DETAIL_GET_SUCCESS = 'MOVIE_DETAIL_GET_SUCCESS';
export const MOVIE_DETAIL_GET_FAILURE = 'MOVIE_DETAIL_GET_FAILURE';

export const MOVIE_RATE = 'MOVIE_RATE';
export const MOVIE_RATE_SUCCESS = 'MOVIE_RATE_SUCCESS';
export const MOVIE_RATE_FAILURE = 'MOVIE_RATE_FAILURE';

export const MOVIE_DELETE_RATING = 'MOVIE_DELETE_RATING';
export const MOVIE_DELETE_RATING_SUCCESS = 'MOVIE_DELETE_RATING_SUCCESS';
export const MOVIE_DELETE_RATING_FAILURE = 'MOVIE_DELETE_RATING_FAILURE';

export const GENRE_DETAIL_CLEAR = 'GENRE_DETAIL_CLEAR';
export const GENRE_DETAIL_GET_REQUEST = 'GENRE_DETAIL_GET_REQUEST';
export const GENRE_DETAIL_GET_SUCCESS = 'GENRE_DETAIL_GET_SUCCESS';
export const GENRE_DETAIL_GET_FAILURE = 'GENRE_DETAIL_GET_FAILURE';

export const FRIEND_DETAIL_CLEAR = 'FRIEND_DETAIL_CLEAR';
export const FRIEND_DETAIL_GET_REQUEST = 'FRIEND_DETAIL_GET_REQUEST';
export const FRIEND_DETAIL_GET_SUCCESS = 'FRIEND_DETAIL_GET_SUCCESS';
export const FRIEND_DETAIL_GET_FAILURE = 'FRIEND_DETAIL_GET_FAILURE';

export const FOLLOWCHECK_DETAIL_CLEAR = 'FOLLOWCHECK_DETAIL_CLEAR';
export const FOLLOWCHECK_DETAIL_GET_REQUEST = 'FOLLOWCHECK_DETAIL_GET_REQUEST';
export const FOLLOWCHECK_DETAIL_GET_SUCCESS = 'FOLLOWCHECK_DETAIL_GET_SUCCESS';
export const FOLLOWCHECK_DETAIL_GET_FAILURE = 'FOLLOWCHECK_DETAIL_GET_FAILURE';

export const FOLLOW_DETAIL_CLEAR = 'FOLLOW_DETAIL_CLEAR';
export const FOLLOW_DETAIL_GET_REQUEST = 'FOLLOW_DETAIL_GET_REQUEST';
export const FOLLOW_DETAIL_GET_SUCCESS = 'FOLLOW_DETAIL_GET_SUCCESS';
export const FOLLOW_DETAIL_GET_FAILURE = 'FOLLOW_DETAIL_GET_FAILURE';